### ISSUE TITLE
Rename the descriptors package to the featurizers package

### ISSUE THREAD

**Issue by richlewis42** [richlewis42/scikit-chem#42]
Descriptors might be considered to != fingerprints.  Featurizers might be considered a better name.

**Comment by mwojcikowski** [comment]
I don't think that descriptors = FPs. "Featurizers" on the other hand is a weird term, which may introduce additional confusion to all, even for people that really think "descriptors = fingerprints".

Especially in scikit-* namespace descriptors are much more widespread and, in my mind, are quite accurate in terms of what they really are in cheminformatics.

**Comment by richlewis42** [comment]
Thanks for your input!  I couldn't decide which way to go.

I agree `Featurizer` is a weird sounding name.  I have heard it used in Machine Learning circles before (not related to cheminformatics), but I used it here mostly just as a contraction of `FeatureCalculator` which was a bit too long.  Before, I had `Fingerprinter` and `DescriptorCalculator` separately, but I thought it was simpler to have a short, single name for both, as in the context of the project they are just for simply calculating features.  

I might change the package name to 'features' to try and keep the names sounding a little less weird, but I would like the name of the module to match the name used for the classes, so `Featurizer`s might have to stay if a better solution doesn't come along.  It should be made a lot clearer in the documentation what they are at least!

**Comment by richlewis42** [comment]
I've changed it to `features` in ed819bc92f5cd45153a09567aba420c36c16248d.  There will be `descriptors`, `atom` and `fingerprints` packages, where modules will define different types of features will be implemented.
