### ISSUE TITLE
standardizer module and standardizer program have different outputs 

### ISSUE THREAD

**Issue by SergeyAnufriev** [richlewis42/scikit-chem#77]
To whom it may concern,

Standardizer module produces different result to standardizer program run by terminal command. I use the same configuration file ['/Users/sergeyanufriev/Desktop/rdkit/std_rules.xml'] for standardizer module and standardize command in terminal. I copied the script and terminal results below. What I am doing wrong? I hope to hear from you. Thank you in advance 

Regards,

Sergey 

1) Standardizer module 

import skchem

std = skchem.standardizers.ChemAxonStandardizer(config_path='/Users/sergeyanufriev/Desktop/rdkit/std_rules.xml') 

m = skchem.Mol.from_smiles('CCC(=O)OCCCC', name='hello')

std.transform(m).to_smiles()

output: 'CCCCOC(=O)CC'

2) Standardizer program [terminal command] 

sergeyanufriev$ standardize 'CCC(=O)OCCCC' -c /Users/sergeyanufriev/Desktop/rdkit/std_rules.xml -f smiles 
output: [H]C([H])([H])C([H])([H])C(=O)OC([H])([H])C([H])([H])C([H])([H])C([H])([H])[H]

**Comment by richlewis42** [comment]
Hi Sergey!  Thanks for the issue, there is certainly some inconsistencies between how this library works with explicit hydrogens and how chemaxon works - I didn't do well at being consistent in this version. I have been working on a complete rewrite (as part of my PhD), so this code is old, and I would rather not look into it as it will be replaced soon.  I will be releasing the new code here asap.
